### ISSUE TITLE
Nunit with ReSharper, Visual Studio Adapter, or TestDriven.NET

### ISSUE THREAD

**Issue by beatsm** [concordion/concordion-net#11]
I have not looked into this much but I can't seem to get the addin to work with Resharper.

I have found this issue:
http://youtrack.jetbrains.com/issue/RSRP-335604#tab=Comments
And this workaround
http://blogs.sourceallies.com/2013/06/nunit-addins-that-works-with-resharper/

Is this something you are likely to support?

Thanks

**Comment by Meai1** [comment]
I would like to just use the nunit-vs-adapter to run both nunit tests and concordion tests.

1. Which side is stalling here? The nunit-vs-adapter or concordion?

Are the following 
1.1 Nunit cannot execute concordion testcases. (not Nunit's problem)
1.2. nunit-vs-adapter cannot find concordion testcases. (not nunit-vs-adapter's problem)

Is this correct? If it is, can you tell me what needs to be done in Concordion to move forward here?

2 . Desired outcome:
2.1 I can see nunit and concordion tests in the Visual Studio "Test Explorer"
2.2 I can execute and debug them from there or from context menu.

3. "NUnit 3.0, to comply with interfaces consumed by ReSharper among others"
If this is the case, does Concordion confirm to these new interfaces already? If not, what needs to be done?
3.1 As far as I understand it, if these correct interfaces were to be used by Concordion, we wouldnt need an nunit addin at all?
3.2 Is the current nunit addin an addin for nunit or the nunit-vs-adapter or both?

// I do *not* care about resharper integration right now.

**Comment by ShaKaRee** [comment]
Hi Meai1,

I am happy that you are keen to engage with Concordion.NET. I will try to provide more information on what needs to be done to move forward.

The idea is to hook up with a popular testing framework, as then the integration to different environments should be easier. The Java version of Concordion is base on JUnit for test execution. With this structure Concordion tests can be executed in IDEs, CI servers, etc. Similarly Concordion.NET provides a NUnit addin to run Concordion.NET tests on any platform that supports NUnit. Otherwise we would have to create an integration for each environment separately.

Concordion.NET tests are different from usual NUnit tests, as they are not represented by test methods but each Concordion specification represents a single test. The Concordion.NET NUnit addin implements the ISuiteBuilder from NUnit and creates NUnit test instances from Concordion specifications:
https://github.com/concordion/concordion-net/blob/master/Concordion.NUnit/Addin/SuiteBuilderAddin.cs

Unfortunately, it is currently not possible to use NUnit addins with the nunit-vs-adapter. To load the addins the nunit-vs-adapter uses the NUnit framework. Thus the fix would be needed in the NUnit implementation itself. Please, find more details in the related issues:
https://bugs.launchpad.net/nunit-vs-adapter/+bug/1193957
https://github.com/nunit/nunit-vs-adapter/issues/9 
But NUnit 2.x will be replace by NUnit 3.x in near future. The work on NUnit 3.0 takes much of the development time. As a result the fixes take some time.

Perhaps you could help to fix the problem in NUnit so that the nunit-vs-adapter would support NUnit addins?

**Comment by ShaKaRee** [comment]
@beatsm, @Meai1,
thank you for your great comments. It helped to create a new version of the Concordion.NET NUnit addin, which allows running Concordion.NET tests with resharper:
https://github.com/concordion/concordion-net/pull/20

**Comment by ShaKaRee** [comment]
NUnit addin to run Concordion.NET tests with ReSharper will be available in the next release (probably March 2015)
